included metaops package for camunda
dbt-labs/hubcap pull request #308
Opened 2024-02-20 11:18 UTC by akozichev

## Description 

DBT Package with the model for Camunda history

Link to your package's repository: 

## Checklist
_This checklist is a cut down version of the [best practices](../blob/main/package-best-practices.md) that we have identified as the package hub has grown. Although meeting these checklist items is not a prerequisite to being added to the Hub, we have found that packages which don't conform provide a worse user experience._

### First run experience
- [ ] (Required): The package includes a [licence file detectable by GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository), such as the Apache 2.0 or MIT licence.
- [ ] The package includes a README which explains how to get started with the package and customise its behaviour
- [ ] The README indicates which data warehouses/platforms are expected to work with this package

### Customisability
- [ ] The package uses ref or source, instead of hard-coding table references.
#### Packages for data transformation (delete if not relevant):
- [ ] provide a mechanism (such as variables) to customise the location of source tables.
- [ ] do not assume database/schema names in sources.

### Dependencies
#### Dependencies on dbt Core
- [ ] The package has set a supported `require-dbt-version` range in `dbt_project.yml`. Example: A package which depends on functionality added in dbt Core 1.2 should set its `require-dbt-version` property to `[">=1.2.0", "<2.0.0"]`.
#### Dependencies on other packages defined in packages.yml:
- [ ] Dependencies are imported from the dbt Package Hub when available, as opposed to a git installation.
- [ ] Dependencies contain the widest possible range of supported versions, to minimise issues in dependency resolution.
- [ ] In particular, dependencies are not pinned to a patch version unless there is a known incompatibility.
### Interoperability
- [ ] The package does not override dbt Core behaviour in such a way as to impact other dbt resources (models, tests, etc) not provided by the package.
- [ ] The package uses the cross-database macros built into dbt Core where available, such as `{{ dbt.except() }}` and `{{ dbt.type_string() }}`.
- [ ] The package disambiguates its resource names to avoid clashes with nodes that are likely to already exist in a project. For example, packages should not provide a model simply called `users`.

### Versioning
- [ ] (Required): The package's git tags validates against the regex defined in [version.py](/hubcap/version.py)
- [ ] The package's version follows the guidance of Semantic Versioning 2.0.0. (Note in particular the recommendation for production-ready packages to be version 1.0.0 or above)

2024-02-23 03:21 UTC, joellabes requested changes
Hey @akozichev, thanks for submitting this! 

I noticed an issue while doing the review. To ensure your users don't have a bad experience, I suggest you provide a way to specify an alternative schema location than `public`, e.g. vars. 
One warning on this note - your README states that source tables are expected to be in `camunda_history`, but the [`schema` config here](https://github.com/metaops-solutions/dbt-camunda/blob/main/models/staging/schema.yml#L5) will [take priority](https://docs.getdbt.com/reference/resource-properties/schema)

Please also move your block in `hub.json` to be alphabetically sorted (this is the only mandatory thing before merge). 

Thanks!

2024-02-28 17:19 UTC, akozichev commented
Hi @joellabes, can you have a look, please?

2024-03-12 14:02 UTC, akozichev commented
can this be approved now? I have fixed the problems.

2024-03-15 02:30 UTC, joellabes approved these changes

2024-03-15 02:35 UTC, merged